name: Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  go_version: 1.21.3

jobs:
  test:
    name: Test with Go on windows-latest
    runs-on: [windows-latest]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}

      - name: go build
        run: |
          go build -v ./...

      - name: go test
        run: |
          go test -shuffle=on -v -count=10 ./...